### ISSUE TITLE
How to add user and password?

### ISSUE THREAD

**Issue by starapple2** [timlebrun/node-icecast-server#2]
How do you add the security credentials?

**Comment by timlebrun** [comment]
Hey there !

This is an old library I wrote as a Proof of Concept years ago, supposed to handle the basics of the "reception" part of an Icecast server. It's pretty Barebone by design and aims at only handling the Icecast input streams, making them available to the program using it.

The [Icecast specs](https://icecast.org/docs/icecast-2.4.0/auth.html) describe the authentication mechanism as simple HTTP Basic, so depending on the use case, you could simply handle the authorization in a reverse proxy, but I will add this as a potential feature addition !

**Comment by starapple2** [comment]
Thanks @timlebrun and looking forward to the feature.
